### ISSUE TITLE
Using Kallisto with other reference species

### ISSUE THREAD

**Issue by rnaraine** [Transipedia/dekupl-run#27]
It is stated that DE-kupl is set up for Human genome only and manual modification of the sources is needed to use another reference. Can you kindly explain which components need to be altered for me to use an alternative species.

Note I am currently running the dekupl using the docker command and my reference organism of interest is Xenopus laevis instead. 

Thank you.

**Comment by dgautheret** [comment]
By default DEKupl-run uses the human Gencode transcriptome for masking. 
To change reference transcriptome, add to the config.json file:

"transcript_fasta":my_transciptome.fa,

For Example:

{
  "fastq_dir": "data",
  "nb_threads": 8,
  "kmer_length": 31,
  "lib_type": "rf",
  "output_dir":"DEkupl_result",
  "diff_method": "DESeq2",
  "chunk_size":1000000,
  "transcript_fasta":my_transciptome.fa,
  "r1_suffix": "_1.fastq.gz",
  "r2_suffix": "_2.fastq.gz",

  "dekupl_counter": {
    "min_recurrence": 2,
    "min_recurrence_abundance": 5
  },

  "diff_analysis": {
    "condition" : {
      "A": "A",
      "B": "B"
    },
    "pvalue_threshold": 0.05,
    "log2fc_threshold": 2
  },

  "samples": [{
      "name": "sample1",
      "condition": "A"
    }, {
      "name" : "sample2",
      "condition" : "A"
    }, {
      "name" : "sample3",
      "condition" : "B"
    }, {
      "name" : "sample4",
      "condition" : "B"
    }
  ]
}

Now you may also want to update the annotation part in DE-kupl annotation. We'll provide the instruction in the Readme for this part ASAP.
