### ISSUE TITLE
dekupl-run docker hangs at test_diff_counts

### ISSUE THREAD

**Issue by samleenz** [Transipedia/dekupl-run#29]
Hi,

I've been trying to run the first part of de-kupl using the Docker image but have been running into issues with the Docker image hanging and failing to write the final outputs (from DESeq2) -- i think it is due to space issues in the docker container due to the logs ("no space left on device" errors). I'm not an expert with Docker though so I may be wrong. There is plenty of space on the server I'm running it on so it is not an issue on storage space on that end.  

 I've attached the log file from the rule that appears to have failed. 

[2018-02-26-test_diff_counts-log.txt](https://github.com/Transipedia/dekupl-run/files/1757377/2018-02-26-test_diff_counts-log.txt)

I'm running `Docker version 1.12.6, build ec8512b/1.12.6`

If I can get this to work without having to manually install all dependencies that would be excellent 

Thanks,

**Comment by jaudoux** [comment]
Hi @samleenz,

I am no specialist of Docker but maybe I can help you.

When you ran the dekupl docker you must have used the `-v` option to specify the directory where dekupl will read/write. Maybe you have different disks on your server, and you are not using the one with a lot of space ?

Anyway, I am going to transfer your request to the person that have built the dekupl docker. I'll keep you in touch.

Best,
Jérôme.
