### ISSUE TITLE
inconsistency between documentation & snakemake file

### ISSUE THREAD

**Issue by leclercfl** [Transipedia/dekupl-run#58]
it seems there is an inconsistency between the documentation and what's in the snakefile for the statistical tests at the gene level; the choice of test is ambiguous if the *gene_diff_method* is not specified in the configuration file. 

in the documentation: 
*gene_diff_method*: Method used for gene differential testing (default: 'DESeq2' or 'limma-voom' if number of samples > 100). Possible choices are 'DESeq2' and 'limma-voom'. 'limma-voom' is a faster alternative for large cohorts.

in the snakemake file (lines 169-174):
AUTOMATICALLY SET GENE DIFF METHOD TO LIMMA-VOOM IF MORE THAN 100 SAMPLES
if 'gene_diff_method' not in config :
    if len(SAMPLE_NAMES) >= 100:
        GENE_DIFF_METH = "DESeq2"
    else:
        GENE_DIFF_METH = "limma-voom"

**Comment by jaudoux** [comment]
@leclercfl Thanks for pointing that out!

Can you make a Pull Request with an updated documentation, please ?

**Comment by MarineAGLAVE** [comment]
I submitted a correction by Pull Request.
And it's been validated! So I close this issue.
